# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: db_arqueio
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: arqueio123
      POSTGRES_USER: arqueio
    ports:
      - 5432:5432

volumes:
 db-data:
